project:
  type: website

website:
  title: "Yanmeng Xing"
  description: "Yanmeng Xing â€” PI at Nanjing University. Research in Science of Science, Complex Networks, and Scientometrics."
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - publication.qmd
      - recruitment.qmd
      - about.qmd
    tools:
      - icon: twitter-x
        href: https://x.com/YanmengXing
      - icon: linkedin
        href: https://linkedin.com/in/yanmeng-xing-03334b193

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


